### ISSUE TITLE
Virtual Keyboard Layouts

### ISSUE THREAD

**Issue by Niko2040** [DaveMDS/epymc#5]
Any way to add the other layouts for the virtual keyboard in EpyMC?

**Comment by DaveMDS** [comment]
Not really atm, but the code has been thinked to support different layouts.
What layout you have in mind? can you provide a mockup?

**Comment by DaveMDS** [comment]
This is now implemented by commit 8d8a027942b3209de9ab8bdf39f7387af7e501ab, 
new layout must be added in the gui.py file using this simple syntax:
```
'en_qwerty': [_('English QWERTY'), 'qwertyuiop()', 'asdfghjkl?-+',   'zxcvbnm.,@'  ]
'en_abc':    [_('English ABC'),    'abcdefghi ()', 'jklmnopqr -@',   'stuvwxyz  .,']
'it_qwerty': [_('Italian QWERTY'), 'qwertyuiopèì', 'asdfghjklòàù',   'zxcvbnm.,@[]']
'it_abc':    [_('Italian ABC'),    'aàbcdeèfghiì', 'jklmnoòpqr()',   'stuùvwxyz.,@']
'symbols':   [_('Symbols'),        '.,:;?!@#$%&^', '+-*/=~°_\'"\\|', '<>()[]{}'    ]
# MOST IMPORTANT SYMBOLS ARE:  . , @ ( )
```

Can you provide me the necessary lines for your language? or just an image of your keyboard layout.
Thanks

**Comment by Jil** [comment]
While not an exact match, let's try:
'fr_azerty': [_('Français AZERTY'), 'azertyuiop()','qsdfghjklm@:', 'wxcvbn,./']

http://static.commentcamarche.net/ccm.net/faq/images/0-Vuskup12-azerty-s-.png

**Comment by DaveMDS** [comment]
Layout dosn't need to exactly match the real keybord, but need to have all the needed chars to be able to write in the relative language.
I think you need to include some special chars for your language, like **ç** and **é**
Also note that **:** and **/** are not needed because they are the "shifted" version of **.** and **@**
Thus you have 5 free space for francais special chars

**Comment by DaveMDS** [comment]
update on this one?
